import TabsAdmin from "@/components/ui/tabsAdmin";
import type { Metadata } from "next";
import { CircleGauge, CirclePlus, BarChart4, Shirt } from 'lucide-react';
import AdminDashboard from "./page";
import AdminDashboardArticles from "./articles/page";
import AdminDashboardCommandes from "./commandes/page";
import AdminDashboardArticleNew from "./new/article/page";
import AdminDashboardNewCategorie from "./new/categorie/page";
import AdminDashboardNewSousCategorie from "./new/sousCategorie/page";
import { getCookie } from "cookies-next";
import { cookies } from "next/headers";


export const metadata: Metadata = {
    title: "Admin Dashboard",
    description: "Generated by create next app",
};

const tabs = [
    {
        title: (
            <div className="flex items-center space-x-2">
                <CircleGauge />
                <p>Dashboard</p>
            </div>
        ),
        value: "dashboard",
        content: (
            <AdminDashboard />
        )
    },
    {
        title: (
            <div className="flex items-center space-x-2">
                <Shirt />
                <p>Articles</p>
            </div>

        ),
        value: "articles",
        content: (
            <AdminDashboardArticles />
        )
    },
    {
        title: (
            <div className="flex items-center space-x-2">
                <BarChart4 />
                <p>Commandes</p>
            </div>

        ),
        value: "commandes",
        content: (
            <AdminDashboardCommandes />
        ),
    },
    {
        title: (
            <div className="flex items-center space-x-2">
                <CirclePlus />
                <p>Ajouter un article</p>
            </div>

        ),
        value: "newArticle",
        content: (
            <AdminDashboardArticleNew />
        ),
    },
    {
        title: (
            <div className="flex items-center space-x-2">
                <CirclePlus />
                <p>Ajouter une catégorie</p>
            </div>

        ),
        value: "newCategorie",
        content: (
            <AdminDashboardNewCategorie />
        ),
    },
    {
        title: (
            <div className="flex items-center space-x-2">
                <CirclePlus />
                <p>Ajouter une sous-catégorie</p>
            </div>

        ),
        value: "newSousCategorie",
        content: (
            <AdminDashboardNewSousCategorie />
        ),
    },
];

export default function AdminLayout() {
    const userData = getCookie("currentUser", { cookies });
    let user;

    if (!userData) {
        return <p>Vous n'êtes pas connecté</p>;
    } else {
        user = JSON.parse(userData as string);
    }

    if (user.role !== "ADMIN") {
        return <p>Vous n'êtes pas autorisé à accéder à cette page</p>;
    }

    return (
        <main>
            <TabsAdmin tabs={tabs} />
        </main>
    );
}
