import TabsAdmin from "@/components/ui/tabsAdmin";
import type { Metadata } from "next";
import { CircleGauge, CirclePlus, BarChart4, Shirt } from 'lucide-react';
import AdminDashboard from "./page";
import AdminDashboardArticles from "./articles/page";
import AdminDashboardCommandes from "./commandes/page";
import AdminDashboardArticleNew from "./articles/new/page";


export const metadata: Metadata = {
    title: "Admin Dashboard",
    description: "Generated by create next app",
};

const tabs = [
    {
        title: (
            <div className="flex items-start space-x-2">
                <CircleGauge />
                <span>Dashboard</span>
            </div>
        ),
        value: "dashboard",
        content: (
            <AdminDashboard />
        )
    },
    {
        title: (
            <div className="flex items-start space-x-2">
                <Shirt />
                <span>Articles</span>
            </div>
        
        ),
        value: "articles",
        content: (
            <AdminDashboardArticles />
        )
    },
    {
        title: (
            <div className="flex items-start space-x-2">
                <BarChart4 />
                <span>Commandes</span>
            </div>
        
        ),
        value: "commandes",
        content: (
            <AdminDashboardCommandes />
        ),
    },
    {
        title: (
            <div className="flex items-start space-x-2">
                <CirclePlus />
                <span>Ajouter un article</span>
            </div>
        
        ),
        value: "newArticle",
        content: (
            <AdminDashboardArticleNew />
        ),
    },
];

export default function AdminLayout() {
    return (
        <main>
            <TabsAdmin tabs={tabs} />
        </main>
    );
}
